server.port=8081

spring.datasource.url=${DB_URL:}
spring.datasource.username=${DB_USER:}
spring.datasource.password=${DB_PASSWORD:}

stripe.secret-key=${STRIPE_SECRET_KEY:}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:8081/stripe/return/success}
stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:8081/stripe/return/cancel}
